package gui.view;

import gui.control.BoardViewMouseListener;
import game.GameLoopService;
import game.pieces.Board;
import gui.control.BoardViewController;
import gui.control.WindowKeyboardListener;
import gui.control.GameStateController;
import gui.control.ScoreController;
import gui.control.SpeedController;
import gui.control.TimeController;
import gui.model.GameModel;
import gui.model.GameModel.GameState;

/**
 * The main window of this application.
 * 
 * @author givanse
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainWindow() {
        initComponents();
        
        this.createNewGame();
        
        this.boardView.addMouseListener(new BoardViewMouseListener(
                             this.boardView, this.textAreaLog, this.gameModel));
        this.addKeyListener(new WindowKeyboardListener(
                             this.boardView, this.textAreaLog, this.gameModel));
        
        new ScoreController(this.scoreField, this.gameModel);
        new SpeedController(this.speedField, this.gameModel);
        new TimeController(this.timeField, this.gameModel);
        new GameStateController(this.textAreaLog, this.gameModel);
        new BoardViewController(this.boardView, this.gameModel); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardView = new gui.view.BoardView();
        jPanel1 = new javax.swing.JPanel();
        buttonNewGame = new javax.swing.JButton();
        buttonPause = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaLog = new javax.swing.JTextArea();
        scoreField = new javax.swing.JTextField();
        speedField = new javax.swing.JTextField();
        timeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Video Game");
        setMinimumSize(new java.awt.Dimension(580, 630));
        setName("Java Game"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                handleKeyTyped(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        boardView.setBackground(gui.view.BoardView.BACKGROUND_COLOR);
        boardView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        boardView.setFocusable(false);
        boardView.setMaximumSize(new java.awt.Dimension(gui.view.BoardView.VIEW_WIDTH, gui.view.BoardView.VIEW_HEIGHT));
        boardView.setPreferredSize(new java.awt.Dimension(gui.view.BoardView.VIEW_WIDTH, gui.view.BoardView.VIEW_HEIGHT));

        javax.swing.GroupLayout boardViewLayout = new javax.swing.GroupLayout(boardView);
        boardView.setLayout(boardViewLayout);
        boardViewLayout.setHorizontalGroup(
            boardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        boardViewLayout.setVerticalGroup(
            boardViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        getContentPane().add(boardView);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Game Data"));

        buttonNewGame.setFocusable(false);
        buttonNewGame.setLabel("<N>ew");
        buttonNewGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNewGameMouseClicked(evt);
            }
        });

        buttonPause.setText("<P>ause");
        buttonPause.setFocusable(false);
        buttonPause.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                handleButtonPauseStateChanged(evt);
            }
        });

        textAreaLog.setEditable(false);
        textAreaLog.setColumns(5);
        textAreaLog.setRows(8);
        textAreaLog.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));
        textAreaLog.setFocusable(false);
        jScrollPane1.setViewportView(textAreaLog);

        scoreField.setEditable(false);
        scoreField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        scoreField.setText("000000000");
        scoreField.setBorder(javax.swing.BorderFactory.createTitledBorder("Score"));
        scoreField.setFocusable(false);

        speedField.setEditable(false);
        speedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        speedField.setText("000");
        speedField.setBorder(javax.swing.BorderFactory.createTitledBorder("Speed"));
        speedField.setFocusable(false);

        timeField.setEditable(false);
        timeField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        timeField.setText("000000000");
        timeField.setBorder(javax.swing.BorderFactory.createTitledBorder("Time"));
        timeField.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(scoreField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                .addComponent(speedField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonNewGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonPause, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(speedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonPause))
                .addGap(3, 3, 3)
                .addComponent(buttonNewGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void handleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_handleKeyTyped
        char keyTyped = evt.getKeyChar();
        if(keyTyped ==  'p' || keyTyped ==  'P')
            this.buttonPause.setSelected(!this.buttonPause.isSelected());
        if(keyTyped ==  'n' || keyTyped ==  'N')
            this.createNewGame();
    }//GEN-LAST:event_handleKeyTyped

    private void handleButtonPauseStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_handleButtonPauseStateChanged
        this.handleEventPauseGame();
    }//GEN-LAST:event_handleButtonPauseStateChanged

    private void buttonNewGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNewGameMouseClicked
        this.createNewGame();
    }//GEN-LAST:event_buttonNewGameMouseClicked

    private void handleEventPauseGame() {
        boolean isPaused = this.buttonPause.isSelected();
        if(isPaused) {
            this.gameModel.setGameState(GameState.PAUSED);
        } else {
            this.gameModel.setGameState(GameState.RUNNING);
        }
    }
    
    private void createNewGame() {
        if(this.gameModel == null) {
            this.textAreaLog.append("New game\n");
            SmartCursor smartCursor = new SmartCursor(Board.WIDTH_IN_SQUARES, 
                                                      Board.HEIGHT_IN_SQUARES);
            this.gameModel = new GameModel(smartCursor);
            this.gameLoopService = new GameLoopService(this.gameModel);
        } else {
            this.textAreaLog.append("Start new game\n");
            this.gameModel.startNewGame();
        }
    }

    public void startGameLoopService() {
        this.gameLoopService.start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | 
                 InstantiationException | 
                 IllegalAccessException | 
                 javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MainWindow mainWindow = new MainWindow();
                mainWindow.setVisible(true);
                mainWindow.startGameLoopService();
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.view.BoardView boardView;
    private javax.swing.JButton buttonNewGame;
    private javax.swing.JToggleButton buttonPause;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField scoreField;
    private javax.swing.JTextField speedField;
    private javax.swing.JTextArea textAreaLog;
    private javax.swing.JTextField timeField;
    // End of variables declaration//GEN-END:variables
    private GameModel gameModel;
    private GameLoopService gameLoopService;
}
